### ISSUE TITLE
Issue with Reflex 0.5.5

### ISSUE THREAD

**Issue by kroo** [kroo/reflex-clerk#6]
Seems like there is also an issue with the new Reflex version 0.5.5 - pydantic cannot be imported from reflex base - I think it's renamed to reflex_main.

**Comment by dentro-innovation** [comment]
In a quick attempt to fix this issue I cloned the repo and replaced all `relflex.base` occurances with `reflex.main` in a first attempt and then `reflex_main` in a 2nd attempt, but didn't solve it. 

How can I find out what I should replace it with?

**Comment by kroo** [comment]
the reason we try to import pydantic from reflex rather than just directly from pydantic was to address an issue with pydantic v2 models in reflex.  [This issue was addressed in 0.5.4](https://github.com/reflex-dev/reflex/pull/3396), so we can just fix this with a conditional import that falls back to `import pydantic`.  I'll put up a PR to address shortly.

**Comment by kroo** [comment]
Resolved in [v1.0.2](https://github.com/kroo/reflex-clerk/releases/tag/v1.0.2)

**Comment by dentro-innovation** [comment]
Thank you, works like a charm again!
